### ISSUE TITLE
Prerendering: Cannot read properties of null (reading 'queryParams')

### ISSUE THREAD

**Issue by GrandSchtroumpf** [mgechev/ngx-quicklink#148]
Hello, when I `prerender` my app I've got this error.
```
TypeError: Cannot read properties of null (reading 'queryParams')
    at containsTree (<dist-path>\server\main.js:1:3389104)
    at Array.some (<anonymous>)
    at PrefetchRegistry.shouldPrefetch (<dist-path>\server\main.js:1:3388802)
    at QuicklinkStrategy.preload (<dist-path>\server\main.js:1:3395113)
    at RouterPreloader.preloadConfig (<dist-path>\server\main.js:1:3310818)
    at RouterPreloader.processRoutes (<dist-path>\server\main.js:1:3310473)
    at RouterPreloader.processRoutes (<dist-path>\server\main.js:1:3310572)
    at RouterPreloader.processRoutes <dist-path>\server\main.js:1:3310572)
    at RouterPreloader.preload (<dist-path>\server\main.js:1:3309888)
    at <dist-path>\server\main.js:1:3309836
```

The function [`containTree`](https://github.com/mgechev/ngx-quicklink/blob/master/projects/ngx-quicklink/src/lib/prefetch-registry.service.ts#L38) expect 2 arguments :
```typescript
export function containsTree(containee: UrlTree, container: UrlTree): boolean {
  return (
    containsQueryParams(container.queryParams, containee.queryParams) &&
    containsSegmentGroup(container.root, containee.root, containee.root.segments)
  );
}
``` 

But the method [`shouldPrefetch`](https://github.com/mgechev/ngx-quicklink/blob/master/projects/ngx-quicklink/src/lib/prefetch-registry.service.ts#L24) provides only one :
```typescript
  shouldPrefetch(url: string) {
    const tree = this.router.parseUrl(url);
    return this.trees.some(containsTree.bind(null, tree));
  }
```
so `container.queryParams` will fail.

**Comment by mgechev** [comment]
Haven't hit this one. Let me know if you find a reproduction, alternatively I can merge your fix and publish.
